name: github-benchmarks
on:
  push:
    branches:
      - develop
  pull_request:
    paths-ignore:
      - '**/*.md'
    types: [ opened, reopened, synchronize ]

permissions: read-all

jobs:
  CI:
    continue-on-error: true
    strategy:
      matrix:
        distro: ['Linux:latest']
        cxx: ['g++']
        backend: ['OPENMP']
    runs-on: kk-pm-login23
    container:
      image: ghcr.io/kokkos/ci-containers/${{ matrix.distro }}
    env:
      BUILD_ID: ${{ matrix.distro }}-${{ matrix.cxx }}-${{ matrix.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/ccache
          key: kokkos-${{ matrix.distro }}-${{ matrix.cxx }}-${{ matrix.backend }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: kokkos-${{ matrix.distro }}-${{ matrix.cxx }}-${{ matrix.backend }}-${{ github.ref }}
      - name: Configure Kokkos
        run: |
          cmake -B builddir \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_${{ matrix.backend }}=ON \
            -DKokkos_ENABLE_BENCHMARKS=ON \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          ccache -z
          NUM_CPU=$(grep -c processor /proc/cpuinfo)
          cmake --build builddir --parallel ${NUM_CPU}
          ccache -s
      - name: Tests
        working-directory: builddir
        run: ctest --output-on-failure
